<?php

namespace App\Collections;

class DeezerGenres
{
    /**
     * @var array
     */
    protected $genres = [
        'Música africana'             => '2',
        'Afro Pop'                    => '3',
        'Biguine'                     => '4',
        'Coupé-Décalé'                => '5',
        'Sega mauritien'              => '6',
        'Swag mauritien'              => '7',
        'Swag mauritien'              => '8',
        'Touareg'                     => '9',
        'Zouglou'                     => '10',
        'Zouk'                        => '11',
        'Música árabe'                => '12',
        'Chaabi'                      => '13',
        'Charki'                      => '14',
        'Raí'                         => '15',
        'Música asiática'             => '16',
        'Pop chino'                   => '18',
        'Pop indonesio'               => '20',
        'J-Pop'                       => '22',
        'K-Pop'                       => '23',
        'Pop malasio'                 => '24',
        'Música de Indonesia'         => '25',
        'Country thai'                => '27',
        'Pop thai'                    => '28',
        'Retro thai'                  => '29',
        'Flamenco'                    => '36',
        'Isklemä'                     => '39',
        'Schlager y Volksmusik'       => '45',
        'Música folk turca'           => '49',
        'Cumbia'                      => '71',
        'Tango'                       => '73',
        'Música Brasileña'            => '75',
        'Axé/Forró'                   => '76',
        'MBP'                         => '78',
        'Samba/Pagode'                => '79',
        'Sertanejo'                   => '80',
        'Música india'                => '81',
        'Country'                     => '84',
        'Alternativo'                 => '85',
        'Pop Indie'                   => '86',
        'Indie Rock'                  => '87',
        'Indie Thai'                  => '88',
        'Indé Finlandaise'            => '89',
        'Indie Estoniano'             => '90',
        'Latino Alternativo'          => '91',
        'Brasileño Alternativo'       => '94',
        'Niños'                       => '95',
        'Nana/Canción de cuna'        => '96',
        'Cuentos'                     => '97',
        'Clásica'                     => '98',
        'Barroca'                     => '99',
        'Época clásica'               => '100',
        'Medieval'                    => '101',
        'Moderna'                     => '102',
        'Ópera'                       => '103',
        'Renacimiento'                => '104',
        'Romántica'                   => '105',
        'Electro'                     => '106',
        'Chill Out/Trip-Hop/Lounge'   => '107',
        'Dubstep'                     => '108',
        'Electro Hip-Hop'             => '109',
        'Electro Pop/Electro Rock'    => '110',
        'Techno/House'                => '111',
        'House sudafricano'           => '112',
        'Dance'                       => '113',
        'Dancefloor'                  => '114',
        'Trance'                      => '115',
        'Rap/Hip Hop'                 => '116',
        'Reggae'                      => '144',
        'Dancehall/Ragga'             => '145',
        'Dub'                         => '146',
        'Ska'                         => '147',
        'Reggae finlandés'            => '149',
        'Reggae mauritano'            => '150',
        'Rock'                        => '152',
        'Blues'                       => '153',
        'Indie Rock/Rock pop'         => '154',
        'Hard Rock'                   => '155',
        'Rock y Roll/Rockabilly'      => '156',
        'Metal finlandés'             => '157',
        'Rock ruso'                   => '158',
        'Rock turco'                  => '159',
        'Rock latino'                 => '160',
        'Rock brasileño'              => '161',
        'Rock finlandés'              => '162',
        'Rock francés'                => '164',
        'R&B'                         => '165',
        'R&B contemporáneo'           => '166',
        'Soul contemporáneo'          => '167',
        'Disco'                       => '168',
        'Soul & Funk'                 => '169',
        'Old School R&B'              => '170',
        'Soul Old School'             => '171',
        'Películas/Juegos'            => '173',
        'Bandas sonoras'              => '174',
        'Musicales'                   => '175',
        'Bandas sonoras'              => '176',
        'Bandas sonoras de TV'        => '177',
        'Bollywood'                   => '178',
        'Música de vídeojuegos'       => '179',
        'Blues acústico'              => '180',
        'Chicago Blues'               => '181',
        'Blues clásico'               => '182',
        'Country Blues'               => '183',
        'Delta Blues'                 => '184',
        'Blues eléctrico'             => '185',
        'Música religiosa'            => '186',
        'Gospel'                      => '187',
        'Religiosa'                   => '188',
        'Pop cristiano'               => '189',
        'Rap cristiano'               => '190',
        'Rock cristiano'              => '191',
        'Country alternativo'         => '192',
        'Bluegrass'                   => '193',
        'Ciencia y medicina'          => '226',
        'Espiritualidad y religión'   => '228',
        'Deportes'                    => '230',
        'Tecnología'                  => '232',
        'Películas y programas de TV' => '332',
        'Música alemana'              => '459',
        'Audiolibros en alemán'       => '462',
        'Metal'                       => '464',
        'Folk'                        => '466',
        'Sélection Deezer'            => '468',
        'Rap/Funk brasileño'          => '472',
        'Moods'                       => '474',
        'Activities'                  => '476',
        'Momentos'                    => '478',
        'Family'                      => '480',
        'Musique Finlandaise'         => '482',
        'Músicas del mundo'           => '484',
        'Infos & Divertissement'      => '486',
        'Afrikaans'                   => '488',
        'Pop sud-africaine'           => '490',
        'Folk sud-africaine'          => '492',
        'Música colombiana'           => '498',
        'Vallenato'                   => '500',
        'Champeta'                    => '502',
        'Salsa Choke'                 => '504',
        'Raizal'                      => '506',
        'Tropical'                    => '534',
        'Soul'                        => '536',
        'Chill'                       => '537',
        'Workout'                     => '539',
        'Fiesta'                      => '541',
        'Feelings & romance'          => '543',
        'Musique russe'               => '544',
        'Histoires criminelles'       => '552',
        'Podcasts internationaux'     => '562',
        'Latin community'             => '572',
        'Adulte'                      => '582',
        'Arts et divertissements'     => '622',
        'Histoire'                    => '632',
        'Géographie'                  => '641',
        'Philosophie'                 => '651',
        'Littérature'                 => '661',
    ];

    public function get()
    {
        return $this->genres;
    }
}

